server:
  port: 8081
spring:
  application:
    name: PROMOCODE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/promocode
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
